web/models/User.php
<?php

/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $user_id
 * @property int|null $group_id
 * @property string|null $first_name
 * @property string|null $last_name
 * @property string|null $email
 * @property string|null $auth_key
 * @property string|null $access_token
 * @property string|null $password
 * @property string|null $password_reset_key
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
	/**
	 * @var
	 */
	public $passwd = '';

	/**
	 * Constants
	 */
	const SCENARIO_CREATE = 'create';
	const SCENARIO_UPDATE = 'update';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    public function behaviors() {
	    $behaviors = parent::behaviors();

	    // auto fill timestamp columns.
	    if ($this->hasAttribute('created_at') || $this->hasAttribute('updated_at')) {
		    $behavior = [
			    'class' => TimestampBehavior::class,
			    'value' => new Expression('NOW()'),
		    ];
		    if ($this->hasAttribute('created_at')) {
			    $behavior['createdAtAttribute'] = 'created_at';
		    } else {
			    $behavior['createdAtAttribute'] = null;
		    }
		    if ($this->hasAttribute('updated_at')) {
			    $behavior['updatedAtAttribute'] = 'updated_at';
		    } else {
			    $behavior['updatedAtAttribute'] = null;
		    }
		    $behaviors[] = $behavior;
	    }
	    return $behaviors;
    }

	/**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
	        [['email', 'first_name', 'last_name'], 'trim'],
	        ['email', 'unique'],
	        ['email', 'email'],
	        [['first_name', 'last_name', 'email'], 'string', 'max' => 100],
	        [['passwd'], 'string', 'length' => [6, 100]],
	        [['group_id'], 'integer'],
	        [['first_name', 'last_name', 'email','passwd'], 'required', 'on' => self::SCENARIO_CREATE],
	        [['first_name', 'last_name', 'email'], 'required', 'on' => self::SCENARIO_UPDATE],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'user_id' => 'User ID',
            'group_id' => 'Group ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'auth_key' => 'Auth Key',
            'access_token' => 'Access Token',
            'password' => 'Password',
	        'passwd'   => 'Password',
            'password_reset_key' => 'Password Reset Key',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

	public function attributeHints() {
		return [
			'first_name'        => \Yii::t('app', 'Enter your First Name'),
			'last_name'         => \Yii::t('app', 'Enter your Last Name'),
			'email'             => \Yii::t('app', 'Enter your Email'),
			'passwd'            => \Yii::t('app', 'Pick your  Password'),
			'group_id'          => \Yii::t('app', 'Pick a Group for this user'),
			'status'            => \Yii::t('app', 'Pick a status for this user'),
		];
	}

	/**
	 * @param bool $insert
	 *
	 * @return bool
	 * @throws \yii\base\Exception
	 */
	public function beforeSave($insert)
	{
		if (!parent::beforeSave($insert)) {
			return false;
		}

		if (!empty($this->passwd)) {
			$this->password = static::hashPassword($this->passwd);
		}
		return true;
	}

	public function getStatusesList()
	{
		return [
			'inactive' => \Yii::t('app', 'Inactive'),
			'active'   => \Yii::t('app', 'Active'),
		];
	}

	/**
	 * @param int|string $user_id
	 *
	 * @return User|IdentityInterface|null
	 */
	public static function findIdentity($user_id)
	{
		return static::findOne($user_id);
	}

	/**
	 * @param mixed $token
	 * @param null $type
	 *
	 * @return User|IdentityInterface|null
	 */
	public static function findIdentityByAccessToken($token, $type = null)
	{
		return static::findOne(['access_token' => $token, 'status' => 'active']);
	}

	/**
	 * @param $email
	 *
	 * @return User|null
	 */
	public static function findByEmail($email)
	{
		return static::findOne(['email' => $email]);
	}

	/**
	 * @param $key
	 *
	 * @return User|null
	 */
	public static function findByPasswordResetKey($key)
	{
		return static::findOne(['password_reset_key' => $key, 'status' => 'active']);
	}

	/**
	 * @return int|string
	 */
	public function getId()
	{
		return $this->user_id;
	}

	/**
	 * @return string|null
	 */
	public function getAuthKey()
	{
		return $this->auth_key;
	}

	/**
	 * @param string $authKey
	 *
	 * @return bool
	 */
	public function validateAuthKey($authKey)
	{
		return $this->getAuthKey() === $authKey;
	}

	/**
	 * @param $password
	 *
	 * @return bool
	 */
	public function validatePassword($password)
	{
		return \Yii::$app->security->validatePassword($password, $this->password);
	}

	/**
	 * @param $password
	 *
	 * @return string
	 * @throws \yii\base\Exception
	 */
	public static function hashPassword($password)
	{
		return \Yii::$app->security->generatePasswordHash($password);
	}

	/**
	 * @return string
	 */
	public function getFullName()
	{
		return trim(sprintf('%s %s', $this->first_name, $this->last_name));
	}
}

web/controllers/UsersController.php
<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Class UsersController
 * @package app\controllers
 */
class UsersController extends \yii\web\Controller
{
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return array
	 */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	/**
	 * @param array $params
	 *
	 * @return $this
	 */
	public function setViewParams(array $params = [])
	{
		$this->view->params = ArrayHelper::merge($this->view->params, $params);
		return $this;
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(\Yii::$app->getRequest()->queryParams);
        $dataProvider->pagination->pageSize=10;

	    \Yii::$app->view->title = \Yii::t('app', 'Users');

        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	/**
	 * @param $id
	 *
	 * @return string
	 * @throws NotFoundHttpException
	 */
    public function actionView($id)
    {
        $model = $this->findModel($id);

	    \Yii::$app->view->title = \Yii::t('app', 'User {userName}', ['userName'=>$model->fullName]);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

	/**
	 * @return string|\yii\web\Response
	 */
    public function actionCreate()
    {
        $model = new User([
            'scenario' => User::SCENARIO_CREATE
        ]);

        \Yii::$app->view->title = \Yii::t('app', 'Create User');

        if ($model->load(\Yii::$app->getRequest()->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
            return $this->render('form', [
                'action'=> 'create',
                'model' => $model,
            ]);
        }
    }

	/**
	 * @param $id
	 *
	 * @return string|\yii\web\Response
	 * @throws NotFoundHttpException
	 */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $user = \Yii::$app->getRequest()->post('User');

        if ($model->load(\Yii::$app->getRequest()->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
        	\Yii::$app->view->title = \Yii::t('app', 'Update {userName}', ['userName'=>$model->fullName]);

            return $this->render('form', [
                'action'=> 'update',
                'model' => $model,
            ]);
        }
    }

	/**
	 * @param $id
	 *
	 * @return \yii\web\Response
	 * @throws NotFoundHttpException
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($id == 1) {
            return $this->redirect(['/users']);
        }

        $model->delete();

        return $this->redirect(['/users']);
    }

	/**
	 * @param $id
	 *
	 * @return User|null
	 * @throws NotFoundHttpException
	 */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/views/users/form.php
<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */

use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use yii\helpers\ArrayHelper;
?>
<div class="content">
    <div class="container-fluid">
        <div class="card ">
    <div class="card-header card-header-primary card-header-icon">
        <div class="card-icon">
            <i class="material-icons">account_box</i>
        </div>
        <h4 class="card-title">
            <?=$model->isNewRecord ? \Yii::t('app', 'Create User') : \Yii::t('app', 'Update User')?>
            <div class="pull-right">
                <?= Html::a(Html::tag('b', 'keyboard_arrow_left', ['class' => 'material-icons']) , ['index'], [
                    'class' => 'btn btn-xs btn-success btn-round btn-fab',
                    'rel'=>"tooltip",
                    'data' => [
                        'placement' => 'bottom',
                        'original-title' => 'Back'
                    ],
                ]) ?>
            </div>
        </h4>
    </div>
    <div class="card-body">
      <?php $form = ActiveForm::begin([
	      'fieldConfig' => [
		      'template' => "{input} {error}",
	      ]
      ]); ?>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group bmd-form-group">
                    <label for="<?=Html::getInputId($model, 'first_name');?>" class="bmd-label-floating"><?=Html::activeLabel($model,'first_name');?></label>
                    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true])->label(false); ?>
                    <span class="bmd-help"><?=Html::activeHint($model,'first_name');?></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group bmd-form-group">
                    <label for="<?=Html::getInputId($model, 'last_name');?>" class="bmd-label-floating"><?=Html::activeLabel($model,'last_name');?></label>
	                <?= $form->field($model, 'last_name')->textInput(['maxlength' => true])->label(false); ?>
                    <span class="bmd-help"><?=Html::activeHint($model,'last_name');?></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group bmd-form-group">
                    <label for="<?=Html::getInputId($model, 'email');?>" class="bmd-label-floating"><?=Html::activeLabel($model,'email');?></label>
	                <?= $form->field($model, 'email')->textInput(['maxlength' => true])->label(false); ?>
                    <span class="bmd-help"><?=Html::activeHint($model,'email');?></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group bmd-form-group">
                    <label for="<?=Html::getInputId($model, 'passwd');?>" class="bmd-label-floating"><?=Html::activeLabel($model,'passwd');?></label>
	                <?= $form->field($model, 'passwd')->textInput(['maxlength' => true])->label(false); ?>
                    <span class="bmd-help"><?=Html::activeHint($model,'passwd');?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer ml-auto mr-auto">
        <?= Html::submitButton($model->isNewRecord ? \Yii::t('app', 'Create') : \Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
	<?php ActiveForm::end(); ?>
</div>
    </div>
</div>

web/views/users/list.php
<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */

use yii\helpers\Html;
    use yii\grid\GridView;
    use yii\widgets\Pjax;
?>
<div class="content">
    <div class="container-fluid">
        <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary card-header-icon">
          <div class="card-icon">
            <i class="material-icons">account_box</i>
          </div>
          <h4 class="card-title">
              Users
              <div class="pull-right">
                <?= Html::a(Html::tag('b', 'add', ['class' => 'material-icons']) , ['create'], [
                    'class' => 'btn btn-xs btn-primary btn-round btn-fab',
                    'rel'=>"tooltip",
                    'data' => [
                        'placement' => 'bottom',
                        'original-title' => 'Add User'
                    ],
                ]) ?>
              </div>
          </h4>
        </div>
        <div class="card-body">
          <div class="material-datatables">
              <?php Pjax::begin([
                  'enablePushState'=>true,
              ]); ?>
              <?= GridView::widget([
                  'id' => 'users',
                  'tableOptions' => [
                      'class' => 'table table-striped table-no-bordered table-hover',
                  ],
                  'options'          => ['class' => 'table-responsive grid-view'],
                  'dataProvider' => $dataProvider,
                  'filterModel' => $searchModel,
                  'columns' => [
                      'first_name',
                      'last_name',
                      'email:email',
                      [
                          'attribute'=>'created_at',
                      ],
                      [
                          'attribute' => 'status',
                          'value'     => function($model) {
                              return\Yii::t('app',ucfirst(\yii\helpers\Html::encode($model->status)));
                          },
                          'filter'    => Html::activeDropDownList($searchModel, 'status', $searchModel->getStatusesList(), ['class' => 'form-control', 'prompt' => 'All'])
                      ],
                      [
                          'header' =>\Yii::t('app','Actions'),
                          'class' => '\yii\grid\ActionColumn',
                          'contentOptions' => [
                              'class'=>'table-actions'
                          ],
                          'template' => '{view} {update} {delete}',
                          'buttons'  => [
	                          'view' => function ($url, $model) {
		                          return Html::a(
			                          '<i class="fa fa-eye"></i>',
			                          \yii\helpers\Url::to(['/users/view', 'id' => $model->user_id]),
			                          [
				                          'rel'                      => "tooltip",
				                          'data-original-title'      => 'View this user',
				                          'data-placement'           => 'top',
				                          'style'                    => 'margin-right: 10px'
			                          ]
		                          );
	                          },
	                          'update' => function ($url, $model) {
		                          return Html::a(
			                          '<i class="fa fa-edit"></i>',
			                          \yii\helpers\Url::to(['/users/update', 'id' => $model->user_id]),
			                          [
				                          'rel'                      => "tooltip",
				                          'data-original-title'      => 'Edit this user',
				                          'data-placement'           => 'top',
				                          'style'                    => 'margin-right: 10px'
			                          ]
		                          );
	                          },
	                          'delete' => function ($url, $model) {
		                          return Html::a(
			                          '<i class="fa fa-trash-o"></i>',
			                          \yii\helpers\Url::to(['/users/delete', 'id' => $model->user_id]),
			                          [
				                          'rel'                      => "tooltip",
				                          'data-original-title'      => 'Delete this user?',
				                          'data-placement'           => 'top',
				                          'data-pjax'                => '0',
				                          'data-confirm'             => 'Are you sure you want to delete this item?',
				                          'data-method'              => 'post',
				                          'style'                    => 'margin-right: 10px'
			                          ]
		                          );
	                          },
                          ]
                      ],
                  ],
              ]); ?>
              <?php Pjax::end(); ?>
          </div>
        </div>
      </div>
    </div>
</div>
    </div>
</div>

web/views/users/view.php
<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */

use yii\helpers\Html;
use yii\widgets\DetailView;
?>
<div class="content">
    <div class="container-fluid">
        <div class="card ">
    <div class="card-header card-header-primary card-header-icon">
        <div class="card-icon">
            <i class="material-icons">account_box</i>
        </div>
        <h4 class="card-title">
            <?=$model->getFullName();?>
            <div class="pull-right">
                <?= Html::a(Html::tag('b', 'keyboard_arrow_left', ['class' => 'material-icons']) , ['index'], [
                    'class' => 'btn btn-xs btn-success btn-round btn-fab',
                    'rel'=>"tooltip",
                    'data' => [
                        'placement' => 'bottom',
                        'original-title' => 'Back'
                    ],
                ]) ?>
                <?= Html::a(Html::tag('b', 'create', ['class' => 'material-icons']) , ['update', 'id' => $model->user_id], [
                    'class' => 'btn btn-xs btn-success btn-round btn-fab',
                    'rel'=>"tooltip",
                    'data' => [
                        'placement' => 'bottom',
                        'original-title' => 'Edit User'
                    ],
                ]) ?>
                <?= Html::a(Html::tag('b', 'delete', ['class' => 'material-icons']), ['delete', 'id' => $model->user_id], [
                    'class' => 'btn btn-xs btn-danger btn-round btn-fab',
                    'rel'=>"tooltip",
                    'data' => [
                        'confirm' => \Yii::t('app', 'Are you sure you want to delete this item?'),
                        'method' => 'post',
                        'placement' => 'bottom',
                        'original-title' => 'Delete User'
                    ],
                ]) ?>
            </div>
        </h4>
    </div>
    <div class="card-body">
        <?= DetailView::widget([
	        'model' => $model,
	        'attributes' => [
		        'user_id',
		        'first_name',
		        'last_name',
		        [
			        'label' => 'Group Name',
			        'value' => ($model->group_id) ? Html::a($model->group->name, ['/admin/groups/view', 'id' => $model->group_id]) : \Yii::t('app', 'No Group'),
			        'format' => 'raw',
		        ],
		        'email:email',
		        [
			        'label' => 'Status',
			        'attribute' => 'status',
			        'value'     => function($model) {
				        return \Yii::t('app',ucfirst(\yii\helpers\Html::encode($model->status)));
			        },
		        ],
		        'created_at',
		        'updated_at',
	        ],
        ]) ?>
    </div>
</div>
    </div>
</div>